apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # already present
  postgres-url: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQHBvc3RncmVzOjU0MzIvdXNlcmRi
  # NEW – base64‑encode whatever secret string you like
  jwt-secret: c3VwZXItc2VjcmV0LWJhbmt4

