name: KubeLinter Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install KubeLinter
      run: |
        curl -sSL https://github.com/stackrox/kube-linter/releases/latest/download/kube-linter-linux.tar.gz | tar -xz
        sudo mv kube-linter /usr/local/bin/

    - name: Run KubeLinter on k8s manifests
      run: kube-linter lint k8s/

