name: Trivy Vulnerability Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and scan user-service
      - name: Build user-service
        run: docker build -t bankx/user-service:latest ./user-service

      - name: Scan user-service with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bankx/user-service:latest
          format: table
          exit-code: 0
          ignore-unfixed: true

      # Build and scan account-service
      - name: Build account-service
        run: docker build -t bankx/account-service:latest ./account-service

      - name: Scan account-service with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bankx/account-service:latest
          format: table
          exit-code: 0
          ignore-unfixed: true

      # Build and scan transaction-service
      - name: Build transaction-service
        run: docker build -t bankx/transaction-service:latest ./transaction-service

      - name: Scan transaction-service with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bankx/transaction-service:latest
          format: table
          exit-code: 0
          ignore-unfixed: true

      # Build and scan analytics-service
      - name: Build analytics-service
        run: docker build -t bankx/analytics-service:latest ./analytics-service

      - name: Scan analytics-service with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: bankx/analytics-service:latest
          format: table
          exit-code: 0
          ignore-unfixed: true

